/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import controller.OpstiKontrolerKI;
import domain.Knjiga;
import exception.ServerskiException;
import java.awt.Font;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import mods.BookMod;
import tablemodel.KnjigeTableModel;

/**
 *
 * @author Mihajlo
 */
public class FrmBook extends javax.swing.JDialog {

    /**
     * Creates new form FrmMember
     */
    public FrmBook() {
        initComponents();
        setSize(1200, 800);
        postaviPrimerke();
        postaviZanrove();
        setTitle("Pretraga knjiga");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnCreateBook = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdBook = new javax.swing.JTextField();
        txtBookName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBook = new javax.swing.JTable();
        btnGetAllBooks = new javax.swing.JButton();
        btnDeleteBooks = new javax.swing.JButton();
        comboGenre = new javax.swing.JComboBox<>();
        btnGetBookByName = new javax.swing.JButton();
        btnPrikaziDetalje = new javax.swing.JButton();

        btnBack.setText("Nazad na glavnu formu");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateBook.setText("Kreiraj novu knjigu");
        btnCreateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBookActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Odaberite kriterijum i vrednost pretrage knjige:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Šifra knjige: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Naziv knjige:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Autor:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Žanr knjige");

        tableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableBook.setRowHeight(30);
        jScrollPane1.setViewportView(tableBook);

        btnGetAllBooks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGetAllBooks.setText("Pretraži primerke");
        btnGetAllBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllBooksActionPerformed(evt);
            }
        });

        btnDeleteBooks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteBooks.setText("Obriši knjigu");
        btnDeleteBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBooksActionPerformed(evt);
            }
        });

        comboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboGenre.setSelectedIndex(-1);

        btnGetBookByName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGetBookByName.setText("Pretraži naslove ");
        btnGetBookByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBookByNameActionPerformed(evt);
            }
        });

        btnPrikaziDetalje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrikaziDetalje.setText("Prikaži detalje");
        btnPrikaziDetalje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziDetaljeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdBook)
                                    .addComponent(txtBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGetAllBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(134, 134, 134)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteBooks, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnPrikaziDetalje, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(btnGetBookByName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGetBookByName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrikaziDetalje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGetAllBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnDeleteBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGetAllBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllBooksActionPerformed
        // TODO add your handling code here:
        //postaviPrimerke();
        HashMap<String,String> kriterijum=new HashMap<>();
        if(!txtIdBook.getText().isEmpty()){
            kriterijum.put("sifraKnjige", txtIdBook.getText());
        }
        if(!txtBookName.getText().isEmpty()){
            kriterijum.put("nazivKnjige",txtBookName.getText());
        }
        if(!txtAutor.getText().isEmpty()){
            kriterijum.put("autorKnjige", txtAutor.getText());
        }
        if(comboGenre.getSelectedIndex()>-1){
            kriterijum.put("zanrKnjige", (String) comboGenre.getSelectedItem());
        }
        comboGenre.setSelectedIndex(-1);
        pronadjiPoKriterijumu(kriterijum);
    }//GEN-LAST:event_btnGetAllBooksActionPerformed

    private void btnGetBookByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBookByNameActionPerformed
        // TODO add your handling code here:
        postaviKnjige();
    }//GEN-LAST:event_btnGetBookByNameActionPerformed

    private void btnCreateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBookActionPerformed
        // TODO add your handling code here:
        FrmBookDetail forma=new FrmBookDetail(BookMod.CREATE_MOD);
        forma.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCreateBookActionPerformed

    private void btnPrikaziDetaljeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziDetaljeActionPerformed
        // TODO add your handling code here:
        int selected=tableBook.getSelectedRow();
        if(selected>-1){
            try{
            Knjiga knjiga=ucitajKnjigu(selected);
            FrmBookDetail forma=new FrmBookDetail(BookMod.CHANGE_MOD, knjiga);
            forma.setVisible(true);
            dispose();
            JOptionPane.showMessageDialog(this, "Ucitana je knjiga sa sifrom:"+knjiga.getSifra());
            } catch(Exception ex){
                JOptionPane.showMessageDialog(this,"Sistem ne moze da ucita knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Morate izabrati jednu knjigu","Izaberite kjigu",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnPrikaziDetaljeActionPerformed

    private void btnDeleteBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBooksActionPerformed
        // TODO add your handling code here:
        int selected=tableBook.getSelectedRow();
        if(selected>-1){
            KnjigeTableModel model=(KnjigeTableModel) tableBook.getModel();
            Knjiga knjiga=model.getKnjige().get(selected);
            obrisiKnjigu(knjiga);
            ((KnjigeTableModel)tableBook.getModel()).obrisiRed(selected, knjiga);
        }else{
            JOptionPane.showMessageDialog(this, "Morate izabrati jednu knjigu","Izaberite kjigu",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteBooksActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateBook;
    private javax.swing.JButton btnDeleteBooks;
    private javax.swing.JButton btnGetAllBooks;
    private javax.swing.JButton btnGetBookByName;
    private javax.swing.JButton btnPrikaziDetalje;
    private javax.swing.JComboBox<String> comboGenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBook;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtIdBook;
    // End of variables declaration//GEN-END:variables

    private void postaviKnjige() {
        try {
            tableBook.setFont(new Font("Serif",Font.PLAIN,15));
            KnjigeTableModel model=new KnjigeTableModel();
           // System.out.println("1");
            List<Knjiga> knjige=OpstiKontrolerKI.getInstance().ucitajKnjige();
            //System.out.println("2");

            model.setKnjige(OpstiKontrolerKI.getInstance().ucitajKnjige());
            tableBook.setModel(model);
        } catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
            dispose();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Doslo je do prekida rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void postaviPrimerke() {
        try {
            tableBook.setFont(new Font("Serif",Font.PLAIN,15));
            KnjigeTableModel model=new KnjigeTableModel();
            model.setKnjige(OpstiKontrolerKI.getInstance().ucitajPrimerke());
            tableBook.setModel(model);
        } catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
            dispose();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Doslo je do prekida rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void postaviZanrove() {
        try {
            DefaultComboBoxModel model=new DefaultComboBoxModel(OpstiKontrolerKI.getInstance().ucitajZanrove().toArray());
            comboGenre.setModel(model);
            comboGenre.setSelectedIndex(-1);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ne moze da se ucita lista zanrova!");
        }
    }

    private void pronadjiPoKriterijumu(HashMap<String, String> kriterijum) {
        try {
            List<Knjiga> nadjeniPrimerci=OpstiKontrolerKI.getInstance().nadjiPrimerke(kriterijum);
            KnjigeTableModel model=new KnjigeTableModel();
            model.setKnjige(nadjeniPrimerci);
            tableBook.setModel(model);
            JOptionPane.showMessageDialog(this, "Pronadjeno je "+nadjeniPrimerci.size()+" knjiga.");
        } catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
            dispose();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje knjige po zadatom kriterijumu","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void obrisiKnjigu(Knjiga knjiga) {
        try {
            boolean uspesan=OpstiKontrolerKI.getInstance().obrisiKnjigu(knjiga);
            if(uspesan){
                JOptionPane.showMessageDialog(this, "Sistem je obrisao knjigu sa sifrom: "+knjiga.getSifra());
            }
        }  catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
            dispose();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Doslo je do prekida rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }

    private Knjiga ucitajKnjigu(int selected) throws Exception {
        KnjigeTableModel model=(KnjigeTableModel) tableBook.getModel();
            int sifra=model.vratiSifru(selected);
            return OpstiKontrolerKI.getInstance().ucitajKnjigu(sifra);
    }
}
