/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import controller.OpstiKontrolerKI;
import domain.Izdavac;
import domain.Knjiga;
import exception.ServerskiException;
import java.text.ParseException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import mods.BookMod;

/**
 *
 * @author Mihajlo
 */
public class FrmBookDetail extends javax.swing.JDialog {

    /**
     * Creates new form FrmMemberDetails
     */
    BookMod mod;
    Knjiga knjiga;
    public FrmBookDetail(BookMod mod){
        //this();
        initComponents();
        setSize(1000, 500);
        this.mod=mod;
        namestiPolja();
    }
    public FrmBookDetail(BookMod mod,Knjiga knjiga){
        //this(mod);
        this.knjiga=knjiga;
        initComponents();
        setSize(1000, 500);
        this.mod=mod;
        namestiPolja();

    }
    public FrmBookDetail() {
        initComponents();
       // namestiPolja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIdBook = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        comboGenre = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtAuthorName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAuthorLastname = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        btnDeleteBook = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnCreateBook = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboIzdavaci = new javax.swing.JComboBox<>();
        btnSacuvajIzmene = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        lblNazivKnjige = new javax.swing.JLabel();
        lblGodina = new javax.swing.JLabel();
        lblZanr = new javax.swing.JLabel();
        lblIzdavac = new javax.swing.JLabel();
        btnKreirajKnjigu = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Šifra knjige:");

        txtIdBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtIdBook.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Naziv knjige:");

        txtBookName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Godina izdavanja:");

        txtYear.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Zanr Knjige:");

        comboGenre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboGenre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboGenre.setSelectedIndex(-1);
        comboGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenreActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ime:");

        txtAuthorName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Prezime:");

        txtAuthorLastname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAutor.setForeground(new java.awt.Color(204, 0, 0));
        lblAutor.setText("Morate uneti pravilno podatke o autoru!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor)
                            .addComponent(txtAuthorLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAuthorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtAuthorLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblAutor)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        btnDeleteBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDeleteBook.setText("Obriši knjigu");
        btnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBookActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Nazad");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateBook.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCreateBook.setText("Zapamti knjigu");
        btnCreateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateBookActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Autor:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Izdavač knjige:");

        comboIzdavaci.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboIzdavaci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboIzdavaci.setSelectedIndex(-1);

        btnSacuvajIzmene.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSacuvajIzmene.setText("Sačuvaj knjigu");
        btnSacuvajIzmene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajIzmeneActionPerformed(evt);
            }
        });

        btnIzmeni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIzmeni.setText("Izmeni podatke");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        lblNazivKnjige.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNazivKnjige.setForeground(new java.awt.Color(204, 0, 0));
        lblNazivKnjige.setText("Morate uneti naziv knjige!!!");

        lblGodina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblGodina.setForeground(new java.awt.Color(204, 0, 0));
        lblGodina.setText("Morate uneti godinu izdavanja!!!");

        lblZanr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblZanr.setForeground(new java.awt.Color(204, 0, 0));
        lblZanr.setText("Morate odabrati zanr knjige!!!");

        lblIzdavac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIzdavac.setForeground(new java.awt.Color(204, 0, 0));
        lblIzdavac.setText("Morate odabrati dobavljaca!!!");

        btnKreirajKnjigu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnKreirajKnjigu.setText("Kreiraj knjigu");
        btnKreirajKnjigu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajKnjiguActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNazivKnjige)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtBookName, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                        .addComponent(txtIdBook))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(btnKreirajKnjigu, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblZanr)
                                                        .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblIzdavac)
                                                        .addComponent(comboIzdavaci, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblGodina)
                                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(11, 11, 11)))
                                    .addComponent(btnCreateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblGodina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(comboGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNazivKnjige)
                    .addComponent(lblZanr))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboIzdavaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblIzdavac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnIzmeni, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnSacuvajIzmene, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(btnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnKreirajKnjigu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCreateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void comboGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGenreActionPerformed

    private void btnCreateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateBookActionPerformed
        // TODO add your handling code here:
        if(proveriPolja()){
            try {
                JOptionPane.showMessageDialog(this, "Uspesno ste popunili polja!");
                zapamtiKnjigu();
                int option=JOptionPane.showConfirmDialog(this, "Da li hocete da kreirate jos knjiga?","Kreiranje clana",JOptionPane.YES_NO_OPTION);
                if(option==0){
                    refresujPolja();
                    kreirajClana();
                    podesiPolja(true);
                }else{
                    dispose();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Nepravilno uneta polja!!","GRESKA",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCreateBookActionPerformed

    private void btnSacuvajIzmeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajIzmeneActionPerformed
        try {
            // TODO add your handling code here:
            // getKnjiga();
            zapamtiKnjigu();
            dispose();
            new FrmBook().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSacuvajIzmeneActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        // TODO add your handling code here:
        namestiPolja(true);
        btnSacuvajIzmene.setEnabled(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        if(knjiga==null && mod==BookMod.CREATE_MOD){
            dispose();
        }
        if(knjiga!=null && mod==BookMod.CREATE_MOD){
            int option=JOptionPane.showConfirmDialog(this, "Da li ste sigurni da hocete da izadjete?\nUkoliko izadjete podaci nece biti sacuvani!","",JOptionPane.YES_NO_OPTION);
            if(option==0){
                try {
                    obrisiKnjigu();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);
                }
                dispose();
            }
        }
        if(mod==BookMod.CHANGE_MOD){
            dispose();
            
        }
        //new FrmBook().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBookActionPerformed
        try {
            // TODO add your handling code here:
            
            obrisiKnjigu();
            dispose();
            new FrmBook().setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteBookActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(knjiga==null){
            dispose();
        }else{
        if(mod==BookMod.CREATE_MOD){
        JOptionPane.showMessageDialog(this, "Podaci o knjizi ce biti obrisani","Izlazak",JOptionPane.CANCEL_OPTION);
            try {
                obrisiKnjigu();
            } catch (Exception ex) {
              JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);  
            }
        }
        //new FrmBook().setVisible(true);
        dispose();
        }

    }//GEN-LAST:event_formWindowClosing

    private void btnKreirajKnjiguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajKnjiguActionPerformed
        try {
            // TODO add your handling code here:
            kreirajClana();
            podesiPolja(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira novu knjigu","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnKreirajKnjiguActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateBook;
    private javax.swing.JButton btnDeleteBook;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreirajKnjigu;
    private javax.swing.JButton btnSacuvajIzmene;
    private javax.swing.JComboBox<String> comboGenre;
    private javax.swing.JComboBox<String> comboIzdavaci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblGodina;
    private javax.swing.JLabel lblIzdavac;
    private javax.swing.JLabel lblNazivKnjige;
    private javax.swing.JLabel lblZanr;
    private javax.swing.JTextField txtAuthorLastname;
    private javax.swing.JTextField txtAuthorName;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtIdBook;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void namestiPolja() {
        namestiCombo();
        namestiErrorLbl();
        switch(mod){
            case CREATE_MOD:
                //kreirajClana();
                setTitle("Kreiranje knjige");
                comboGenre.setSelectedIndex(-1);
                comboIzdavaci.setSelectedIndex(-1);
                btnDeleteBook.setEnabled(false);
                btnIzmeni.setEnabled(false);
                btnSacuvajIzmene.setEnabled(false);
                podesiPolja(false);
                break;
            case CHANGE_MOD:
                setKnjiga();
                setTitle("Izmena podataka knjige");
                namestiPolja(false);
                btnCreateBook.setEnabled(false);
                btnSacuvajIzmene.setEnabled(false);
                btnKreirajKnjigu.setEnabled(false);
                break;
                
                
                
        }
    }

    private void namestiCombo() {
        try {
            DefaultComboBoxModel modelZ=new DefaultComboBoxModel( OpstiKontrolerKI.getInstance().ucitajZanrove().toArray());
            comboGenre.setModel(modelZ);
            DefaultComboBoxModel modelI=new DefaultComboBoxModel(OpstiKontrolerKI.getInstance().ucitajIzdavace().toArray());
            comboIzdavaci.setModel(modelI);
        } catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, "Ne moze se ucitati lista zanrova ili izdavaca!","GRESKA",JOptionPane.ERROR_MESSAGE);
        } catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Prekid rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void kreirajClana() throws Exception {
        
            knjiga=OpstiKontrolerKI.getInstance().kreirajKnjigu(knjiga);
            if(knjiga!=null){
                txtIdBook.setText(String.valueOf(knjiga.getSifra()));
                JOptionPane.showMessageDialog(this,"Kreirana je knjiga sa sifrom "+knjiga.getSifra());
            }
        
    }
    private void namestiErrorLbl(){
        lblNazivKnjige.setVisible(false);
        lblGodina.setVisible(false);
        lblZanr.setVisible(false);
        lblIzdavac.setVisible(false);
        lblAutor.setVisible(false);
    }
    private boolean proveriPolja(){
        boolean uspesan=true;
        if(txtBookName.getText().isEmpty()){
            uspesan=false;
            lblNazivKnjige.setVisible(true);
        }else{
            lblNazivKnjige.setVisible(false);
        }
        
        try{
        int year=Integer.parseInt(txtYear.getText());
        } catch (NumberFormatException ex){
            uspesan=false;
            lblGodina.setVisible(true);
        }
        
        if(txtYear.getText().isEmpty()){
            uspesan=false;
            lblGodina.setVisible(true);
        }else{
            lblGodina.setVisible(false);
        }
        
        if(txtAuthorName.getText().isEmpty() || txtAuthorLastname.getText().isEmpty()){
            uspesan=false;
            lblAutor.setVisible(true);
        }else{
            lblAutor.setVisible(false);
        }
        
        if(comboGenre.getSelectedIndex()==-1){
            uspesan=false;
            lblZanr.setVisible(true);
        }else{
            lblZanr.setVisible(false);
        }
        
        if(comboIzdavaci.getSelectedIndex()==-1){
            uspesan=false;
            lblIzdavac.setVisible(true);
        }else{
            lblIzdavac.setVisible(false);
        }
        return uspesan;
    }

    private void zapamtiKnjigu() throws Exception {
        
            getKnjiga();
            boolean uspesan=OpstiKontrolerKI.getInstance().zapamtiKnjigu(knjiga);
            if(uspesan){
                JOptionPane.showMessageDialog(this, "Uspesno ste zapamtili knjigu sa sifrom"+knjiga.getSifra());
                //dispose();
            }
        
        if(mod==BookMod.CHANGE_MOD){
            new FrmBook().setVisible(true);
        }
    }

    private void getKnjiga() {
        knjiga.setNaziv(txtBookName.getText());
        knjiga.setGodinaIzdavanja(Integer.parseInt(txtYear.getText()));
        knjiga.setZanr((String) comboGenre.getSelectedItem());
        knjiga.setIzdavac((Izdavac) comboIzdavaci.getSelectedItem());
        knjiga.setAutor(txtAuthorName.getText()+" "+txtAuthorLastname.getText());
        
        
    }

    private void obrisiKnjigu() throws Exception {
        
            boolean uspesan=OpstiKontrolerKI.getInstance().obrisiKnjigu(knjiga);
            if(uspesan){
               JOptionPane.showMessageDialog(this, "Obrisana je knjiga sa sifrom: "+knjiga.getSifra());
            }
        
    }

    private void setKnjiga() {
        txtIdBook.setText(String.valueOf(knjiga.getSifra()));
        txtBookName.setText(knjiga.getNaziv());
        String[] reci=knjiga.getAutor().split(" ");
        txtAuthorName.setText(reci[0]);
        txtAuthorLastname.setText(reci[1]);
        txtYear.setText(String.valueOf(knjiga.getGodinaIzdavanja()));
        comboGenre.getModel().setSelectedItem(knjiga.getZanr());
        comboIzdavaci.getModel().setSelectedItem(knjiga.getIzdavac());
    }

    private void namestiPolja(boolean b) {
        txtAuthorName.setEnabled(b);
        txtAuthorLastname.setEnabled(b);
        txtBookName.setEnabled(b);
        txtYear.setEnabled(b);
        comboGenre.setEnabled(b);
        comboIzdavaci.setEnabled(b);
    }

    private void podesiPolja(boolean b) {
        btnKreirajKnjigu.setEnabled(!b);
        btnCreateBook.setEnabled(b);
        txtBookName.setEditable(b);
        txtAuthorName.setEditable(b);
        txtAuthorLastname.setEditable(b);
        txtYear.setEditable(b);
        comboGenre.setEditable(b);
        comboIzdavaci.setEditable(b);
        //btnDeleteBook.setEnabled(b);
        
    }

    private void refresujPolja() {
        txtIdBook.setText("");
        txtBookName.setText("");
        txtAuthorName.setText("");
        txtAuthorLastname.setText("");
        txtYear.setText("");
        comboGenre.setSelectedIndex(-1);
        comboIzdavaci.setSelectedIndex(-1);
    }
}
