/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domain.Bibliotekar;
import domain.Clan;
import exception.ServerskiException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.OpstiKontrolerClanaKI;
// kontroler.OpstiKontrolerKI;

/**
 *
 * @author Mihajlo
 */
public class FrmLoginMember extends javax.swing.JDialog {

    /**
     * Creates new form FrmLoginAdmin
     */
    private Clan clan;
    public FrmLoginMember(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        upozorenja();
        setTitle("Prijava clana");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtLozinka = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblUpozorenjeEmail = new javax.swing.JLabel();
        lblUpozorenjeLozinka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Dobro došli, prijavite se kako bi nastavili sa radom!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Email:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Lozinka:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Prijavi se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblUpozorenjeEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUpozorenjeEmail.setForeground(new java.awt.Color(255, 51, 51));
        lblUpozorenjeEmail.setText("Morate uneti ispravno email u formatu .com");

        lblUpozorenjeLozinka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUpozorenjeLozinka.setForeground(new java.awt.Color(255, 51, 51));
        lblUpozorenjeLozinka.setText("Morate uneti  lozinku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUpozorenjeEmail)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblUpozorenjeLozinka)
                                        .addComponent(txtLozinka))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblUpozorenjeEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUpozorenjeLozinka)
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            uspostaviKonekciju();
            String email=txtEmail.getText();
            String lozinka=txtLozinka.getText();
            if(proveriEmail() && proveriLozinku()){
                upozorenja();
                ulogujClana(email,lozinka);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Ne mozete se povezati na server!\nPokusajte kasnije","GRESKA",JOptionPane.ERROR_MESSAGE);
        } catch(ServerskiException ex){
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Doslo je do greske prilikom pretrage Clana!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            raskiniKonekciju();
            //System.exit(0);
        } catch (Exception ex) {
            System.out.println("RASKONEKTOVAN");
            //ex.printStackTrace();
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblUpozorenjeEmail;
    private javax.swing.JLabel lblUpozorenjeLozinka;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLozinka;
    // End of variables declaration//GEN-END:variables

    private void uspostaviKonekciju() throws IOException {
        OpstiKontrolerClanaKI.getInstance().uspostaviKonekciju();
    }

    

    private void upozorenja() {
        lblUpozorenjeEmail.setVisible(false);
        lblUpozorenjeLozinka.setVisible(false);
    }

    private boolean proveriEmail() {
        if(txtEmail.getText().equals("")){
            lblUpozorenjeEmail.setVisible(true);
            return false;
            }
        return true;
    }

    private boolean proveriLozinku(){
        if(txtLozinka.getText().equals("")){
            lblUpozorenjeLozinka.setVisible(true);
            return false;
        }
        return true;
    }

    private void raskiniKonekciju() throws Exception {
        OpstiKontrolerClanaKI.getInstance().raskiniKonekciju();
    }

    private void ulogujClana(String email, String lozinka) throws ServerskiException,Exception {
       clan=new Clan();
       clan=OpstiKontrolerClanaKI.getInstance().prijaviClana(email, lozinka);
       if(clan==null){
           JOptionPane.showMessageDialog(this, "Neuspesna prijava na sistem","Prijava",JOptionPane.WARNING_MESSAGE);
       }else{
           JOptionPane.showMessageDialog(this, "Uspesna prijava na sistem");
           dispose();
           new FrmBookView(clan).setVisible(true);
       }
    }

    
}
