/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.OpstiKontrolerKI;
import domain.Clan;
import domain.Rezervacija;
import exception.ServerskiException;
import java.awt.Font;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tablemodel.ClanoviTableModel;
import tablemodel.KnjigeTableModel;
import tablemodel.StavkeRezervacijeModel;

/**
 *
 * @author Mihajlo
 */
public class FrmReservationConfirm extends javax.swing.JDialog {

    /**
     * Creates new form FrmReservationConfirm
     */
    ClanoviTableModel modelClanovi;
    KnjigeTableModel modelStavke;
    Rezervacija rezervacija;
    public FrmReservationConfirm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        namestiPolja();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClanovi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStavke = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSifraRezervacije = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDatumIznamljivanja = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDatumVracanja = new javax.swing.JTextField();
        btnPotvrdi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnPretraziClanove = new javax.swing.JButton();
        btnProveri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Telefon:");

        txtTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tableClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableClanovi);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableStavke);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Šifra Rezervacije:");

        txtSifraRezervacije.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSifraRezervacije.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Datum Iznamljivanja:");

        txtDatumIznamljivanja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDatumIznamljivanja.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Datum Vraćanja:");

        txtDatumVracanja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDatumVracanja.setEnabled(false);
        txtDatumVracanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumVracanjaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSifraRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDatumVracanja))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtDatumIznamljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifraRezervacije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtDatumIznamljivanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDatumVracanja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        btnPotvrdi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPotvrdi.setText("Potvrdi");
        btnPotvrdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotvrdiActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Nazad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnPretraziClanove.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPretraziClanove.setText("Pretraži");
        btnPretraziClanove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziClanoveActionPerformed(evt);
            }
        });

        btnProveri.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProveri.setText("Proveri");
        btnProveri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnPretraziClanove, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPotvrdi, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProveri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretraziClanove, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProveri, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btnPotvrdi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDatumVracanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumVracanjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumVracanjaActionPerformed

    private void btnPretraziClanoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziClanoveActionPerformed
        // TODO add your handling code here:
        HashMap<String,String> kriterijum=new HashMap<>();
        if(!txtTelefon.getText().isEmpty()){
            kriterijum.put("telefonClana",txtTelefon.getText());
        }
        try {
            modelClanovi.setClanovi(OpstiKontrolerKI.getInstance().nadjiClanove(kriterijum));
            tableClanovi.setModel(modelClanovi);
        } catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
        } catch( Exception ex){
            JOptionPane.showMessageDialog(this,"Doslo je do prekida rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnPretraziClanoveActionPerformed

    private void btnProveriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveriActionPerformed
        // TODO add your handling code here:
        int selected=tableClanovi.getSelectedRow();
        if(selected==-1){
            JOptionPane.showMessageDialog(this, "Morate odabrati jednog clana!","Upozorenje",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                setRezervacija(selected); 
                ucitajRezervacije();
            } catch (ServerskiException ex) {
                JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex){
                JOptionPane.showMessageDialog(this, "Doslo je do prekida rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnProveriActionPerformed

    private void btnPotvrdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotvrdiActionPerformed
        try {
            // TODO add your handling code here:
            boolean uspesno=potvrdiRezervaciju();
            if(uspesno){
                JOptionPane.showMessageDialog(this,"Uspesno ste izvrsili potvrdu rezervacije");
            }else{
                JOptionPane.showMessageDialog(this, "Neuspesna opcija potvrde rezervacije","Neuspesna potvrda",JOptionPane.WARNING_MESSAGE);
            }
            dispose();
        } catch (ServerskiException ex) {
            JOptionPane.showMessageDialog(this, ex,"GRESKA",JOptionPane.ERROR_MESSAGE);
        } catch( Exception ex){
            JOptionPane.showMessageDialog(this,"Doslo je do prekida rada servera!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPotvrdiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPotvrdi;
    private javax.swing.JButton btnPretraziClanove;
    private javax.swing.JButton btnProveri;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableClanovi;
    private javax.swing.JTable tableStavke;
    private javax.swing.JTextField txtDatumIznamljivanja;
    private javax.swing.JTextField txtDatumVracanja;
    private javax.swing.JTextField txtSifraRezervacije;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables

    private void namestiPolja() {
        try {
            namestiTabeleKnjige();
            namestiTabeluClanovi();
            tableStavke.setEnabled(false);
            btnPotvrdi.setEnabled(false);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Ne moze se ucitati lista objekata!","GRESKA",JOptionPane.ERROR_MESSAGE);
        }

    }

    private void namestiTabeleKnjige() {
       modelStavke=new KnjigeTableModel();
       tableStavke.setFont(new Font("Serif",Font.PLAIN,14));
       tableStavke.setModel(modelStavke);
    }

    private void namestiTabeluClanovi() throws Exception {
       modelClanovi=new ClanoviTableModel();
            tableClanovi.setFont(new Font("Serif",Font.PLAIN,14));
            //ClanoviTableModel model=new ClanoviTableModel();
            modelClanovi.setClanovi(OpstiKontrolerKI.getInstance().ucitajSveClanove());
            setTitle("Potvrdi rezervaciju");
            tableClanovi.setModel(modelClanovi); 
    }

    private void ucitajRezervacije() throws ServerskiException,Exception {
        List<Rezervacija> rezervacije=OpstiKontrolerKI.getInstance().ucitajRezervacijePoClanu(rezervacija);
        if(rezervacije.size()>0){
          FrmSelectReservation forma=new FrmSelectReservation(this,true);
          forma.setRezervacije(rezervacije);
          forma.setForma(this);
          forma.namestiPolja();
          forma.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Nema rezervacija za datog clana!","Rezervacije",JOptionPane.WARNING_MESSAGE);
        }
    }

    private void setRezervacija(int selected) {
        rezervacija=new Rezervacija();
        Clan clan=((ClanoviTableModel)tableClanovi.getModel()).getClanovi().get(selected);
        rezervacija.setClan(clan);
    }

    void namestiRezervaciju(Rezervacija rezervacija) {
        this.rezervacija=rezervacija;
    }

    void getRezervacija() {
        txtSifraRezervacije.setText(String.valueOf(rezervacija.getSifra()));
        txtDatumIznamljivanja.setText(rezervacija.getDatumIznamljivanja().toString());
        txtDatumVracanja.setText(rezervacija.getDatumVracanja().toString());
        StavkeRezervacijeModel model=new StavkeRezervacijeModel();
        model.setStavke_rezervacije(rezervacija.getStavkeRezervacije());
        tableStavke.setModel(model);
        if(rezervacija.isAktivnostRezervacije()){
            btnPotvrdi.setEnabled(true);
        }
    }

    private boolean potvrdiRezervaciju() throws Exception {
        return OpstiKontrolerKI.getInstance().potvrdiRezervaciju(rezervacija);
    }
}
