/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domain.Rezervacija;
import java.awt.Font;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import tablemodel.RezervacijaTableModel;

/**
 *
 * @author Mihajlo
 */
public class FrmSelectReservation extends javax.swing.JDialog {

    /**
     * Creates new form FrmSelectReservation
     */
    private List<Rezervacija> rezervacije;
    private FrmReservationConfirm forma;

    public FrmReservationConfirm getForma() {
        return forma;
    }

    public void setForma(FrmReservationConfirm forma) {
        this.forma = forma;
    }
    public FrmSelectReservation(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        rezervacije=new LinkedList<>();
        setTitle("Odabir rezervacija");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRezervacije = new javax.swing.JTable();
        btnIzaberi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableRezervacije);

        btnIzaberi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnIzaberi.setText("Izaberi");
        btnIzaberi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnIzaberi, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIzaberi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiActionPerformed
        // TODO add your handling code here:
        int selected=tableRezervacije.getSelectedRow();
        if(selected>-1){
            Rezervacija rezervacija=((RezervacijaTableModel)tableRezervacije.getModel()).getRezervacije().get(selected);
            forma.namestiRezervaciju(rezervacija);
            forma.getRezervacija();
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Morate odabrati jednu rezervaciju");
        }
        
    }//GEN-LAST:event_btnIzaberiActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRezervacije;
    // End of variables declaration//GEN-END:variables

    public List<Rezervacija> getRezervacije() {
        return rezervacije;
    }

    public void setRezervacije(List<Rezervacija> rezervacije) {
        this.rezervacije = rezervacije;
    }

    void namestiPolja() {
        RezervacijaTableModel model=new RezervacijaTableModel();
        tableRezervacije.setFont(new Font("Serif",Font.PLAIN,14));
        model.setRezervacije(rezervacije);
        tableRezervacije.setModel(model);
    }
}
