/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package operations;

/**
 *
 * @author Mihajlo
 */
public enum Operation {
    PRIJAVI_BIBLIOTEKARA,
    UCITAJ_GRADOVE,
    UCITAJ_VRSTE_CLANSKIH_KARATA,
    KREIRAJ_CLANA,
    ZAPAMTI_CLANA,
    UCITAJ_CLANA,
    UCITAJ_SVE_CLANOVE,
    NADJI_CLANOVE,
    AKTIVIRAJ_CLANSTVO,
    DEAKTIVIRAJ_CLANSTVO,
    OBRISI_CLANA,
    UCITAJ_ZANROVE,
    UCITAJ_IZDAVACE,
    KREIRAJ_KNJIGU,
    ZAPAMTI_KNJIGU,
    OBRISI_KNJIGU,
    UCITAJ_PRIMERKE,
    UCITAJ_KNJIGE,
    UCITAJ_KNJIGU,
    NADJI_PRIMERKE,
    NADJI_SLOBODNE_PRIMERKE,
    KREIRAJ_REZERVACIJU,
    ZAPAMTI_REZERVACIJU,
    OBRISI_REZERVACIJU,
    UCITAJ_REZERVACIJE_PO_CLANU,
    POTVRDI_REZERVACIJU,
    UCITAJ_DOBAVLJACE,
    KREIRAJ_NARUDZBENICU,
    ZAPAMTI_NARUZBENICU,
    OBRISI_NARUDZBENICU,
    IZLOGUJ_SE,
    PROVERA_EMAIL,
    PRIJAVA_CLANA,
    TERMINATE;
}
